void connectToNetwork();
void printWiFiData();
void printCurrentNet();
void printMacAddress(byte mac[]);
void pingGoogle();
bool isDeviceNeedToFeed(int deviceId);
void deleteFeedFromServer(String feedId);
String GetResponse();
bool IsResponseContainsFeeds(String response);
void RemoveAllFeedsInResponse(String response);
int GetFeedsCountFromResponse(String response);
